#!/bin/bash -e
while :
do
    cryspy
    LOG_LASTLINE=`tail -n 1 log_cryspy`
    if  [ "$LOG_LASTLINE" = "Done all structures!" ]
    then
        exit 0
    elif [ "$LOG_LASTLINE" = "LAQA is ready" ]
    then
        # ---------- for LAQA
        cryspy    # selection
        cryspy    # submit jobs
    fi
    sleep 2m
done
